### ISSUE TITLE
Simplify layout

### ISSUE THREAD

**Issue by SebastienHUGDELARAUZE** [IMT-Atlantique-FIP2021/fiowebviewer-frontend#10]
Test layout divided in 3 zones (like in Nginx Proxy Manager)

**Comment by SebastienHUGDELARAUZE** [comment]
[TailwindPlay | Dark mode](https://play.tailwindcss.com/QYUisW7RKu?size=1220x740)

![image](https://user-images.githubusercontent.com/25550343/108899227-7b9b4c80-7618-11eb-9eb8-61337d6325e4.png)

**Comment by damonmolina** [comment]
Tailwind Playground L27: Result Explorer -> <input type="text" placeholder=" Search..">

**Comment by SebastienHUGDELARAUZE** [comment]
Merge done
