### ISSUE TITLE
Header checkbox need to select all

### ISSUE THREAD

**Issue by SebastienHUGDELARAUZE** [IMT-Atlantique-FIP2021/fiowebviewer-frontend#6]
Header checkbox need to select all checkbox and give the right value when form compared is submitted.

Example: https://stackoverflow.com/questions/33571382/check-all-checkboxes-vuejs#38033792

**Comment by damonmolina** [comment]
React select all boxes: https://codesandbox.io/s/vvxpny4xq3

**Comment by damonmolina** [comment]
Example: https://codesandbox.io/s/grouped-checkboxes-v5sww
